const WebSocket = require('ws');
const os = require('os');
const fetch = require('node-fetch');
const FormData = require('form-data');
const fs = require('fs');
const path = require('path');

const port = 40002;
const url = 'http://localhost:8000/ask'; 

//potential bug fix
const maxAnswerLength = 300;

const wss = new WebSocket.Server({ host: '0.0.0.0', port: port });

//session id for every participant
const sessionId = String(Math.floor(Math.random() * 900000000) + 100000000);

// logging metrics
const metrics = path.join(__dirname, "metrics");
const metricsStreams = new Map();  
const pendingRequests = new Map();  

// Stores connected clients by role
const clients = {
    browser: null,
    unity: null
};

const ips = GetLocalIPs();
ips.forEach(ip => {
    ConsoleLog(`Server reachable at: ws://${ip}:${port}`);
});
ConsoleLog(`Session ID (generated at server startup): ${sessionId}`);

wss.on('connection', (ws, req) => 
{
    const ip = req.socket.remoteAddress;
    ConsoleLog(`New connection from ${ip}`);

    let role = 'unknown';

    ws.on('message', (rawMessage, isBinary) => {
        try {
            let data;
            let imageBuffer = null;

            if (isBinary) {
                // base64
                const jsonLen = rawMessage.readUInt32BE(0);
                const jsonStr = rawMessage.slice(4, 4 + jsonLen).toString('utf8');
                data = JSON.parse(jsonStr);

                if (rawMessage.length > 4 + jsonLen) {
                    imageBuffer = rawMessage.slice(4 + jsonLen);
                }
            } else {
                data = JSON.parse(rawMessage.toString());
            }

            // registration
            if (data.type === 'register') {
                role = data.role;
                clients[role] = ws;
                ConsoleLog(`Client registered as: ${role}`);

                // Unity receives the session ID generated by the server
                if (role === 'unity') {
                    ws.send(JSON.stringify({ type: 'session', sessionId: sessionId }));
                    ConsoleLog(`Session ID sent to Unity: ${sessionId}`);
                }

                logCurrentClients();
                return;
            }

            // heartbeat
            if (data.type === 'pong') {
                return;
            }

            // request
            if (data.type === 'request') {
                // Fallback: if the client does not (yet) provide a session ID, use the server ID
                if (!data.sessionId || String(data.sessionId).trim() === '') {
                    data.sessionId = sessionId;
                }
                const reqSessionId = data.sessionId ?? '(no sessionId)';
                const question = data.question ?? '(no question)';
                const assistanceMode = data.assistanceMode ?? '(no mode)';
                const hasImage = !!data.image;

                ConsoleLog(`Request from ${role} | Mode: ${assistanceMode} | Session: ${reqSessionId} | Question: ${question} | Image: ${hasImage ? 'yes' : 'no'}`);

                if (imageBuffer) {
                    data.image = imageBuffer.toString('base64');
                }

                // metrics: incoming request
                pendingRequests.set(data.sessionId, Date.now());
                writeMetricsLog(data.sessionId, {
                    event: 'request',
                    role,
                    assistanceMode: data.assistanceMode ?? null,
                    question: typeof data.question === 'string' ? data.question : null,
                    questionLength: typeof data.question === 'string' ? data.question.length : null,
                    hasImage: !!(imageBuffer || data.image)
                });

                if (data.assistanceMode === 'AiAssistance') {
                    handleAiAssistance(data);
                } else if (data.assistanceMode === 'HumanAssistance') {
                    handleHumanAssistance(data);
                } else {
                    ConsoleLog(`Unknown assistanceMode: ${data.assistanceMode}`);
                }
                return;
            }

            // response
            if (data.type === 'response') {
                const sessionId = data.session_id ?? '(no session_id)';

                // latency measurement
                const startedAt = pendingRequests.get(data.session_id);
                const latencyMs = startedAt != null ? Date.now() - startedAt : null;
                const durationSeconds = latencyMs != null ? +(latencyMs / 1000).toFixed(3) : null;
                pendingRequests.delete(data.session_id);

                const answer = typeof data.answer === 'string' ? data.answer : null;
                ConsoleLog(`Answer from ${role} | Session: ${sessionId} | Duration: ${durationSeconds ?? '?'}s | Answer: ${answer ?? '(none)'}`);

                writeMetricsLog(data.session_id, {
                    event: 'response',
                    assistanceMode: 'HumanAssistance',
                    durationSeconds,
                    latencyMs,
                    answer,
                    answerLength: answer != null ? answer.length : null
                });

                sendToUnity({
                    session_id:     data.session_id ?? null,
                    answer:         data.answer     ?? '',
                    image_url:      data.image_url  ?? '',
                    audio_url:      data.audio_url  ?? '',
                    boxes:          data.boxes      ?? []
                });
                return;
            }

            ConsoleLog(`Unknown message type from ${role}: ${data.type}`);

        } catch (err) {
            ConsoleLog(`Error processing message from ${ip}: ${err}`);
        }
    });

    ws.on('close', () => {
        ConsoleLog(`Connection closed (${role})`);
        if (clients[role] === ws) {
            clients[role] = null;
        }
        logCurrentClients();
    });

    ws.on('error', (err) => {
        ConsoleLog(`WebSocket error (${role}): ${err}`);
    });
});

// forward human assistance
function handleHumanAssistance(data) {
    const target = clients['browser'];
    if (target && target.readyState === WebSocket.OPEN) {
        target.send(JSON.stringify(data));
        ConsoleLog(`HumanAssistance forwarded -> Browser`);
        ConsoleLog(`Full JSON -> Browser:\n${JSON.stringify(data, null, 2)}`);
    } else {
        ConsoleLog(`HumanAssistance: No browser connected`);
    }
}

// ai assistance
async function handleAiAssistance(data) {
    try {
        const form = new FormData();
        form.append('question', data.question ?? '');
        form.append('session_id', data.sessionId ?? '');
        form.append('language', data.language ?? 'german');

        if (data.image) {
            // image is expected as a Base64 string
            const imageBuffer = Buffer.from(data.image, 'base64');
            form.append('image', imageBuffer, { filename: 'image.jpg', contentType: 'image/jpeg' });
        }

        ConsoleLog(`API call to ${url} | Session: ${data.sessionId}`);

        const aiResponse = await fetch(url, { method: 'POST', body: form });

        // ai answer latency
        const startedAt = pendingRequests.get(data.sessionId);
        const latencyMs = startedAt != null ? Date.now() - startedAt : null;
        const durationSeconds = latencyMs != null ? +(latencyMs / 1000).toFixed(3) : null;
        pendingRequests.delete(data.sessionId);

        if (!aiResponse.ok) {
            ConsoleLog(`API error: HTTP ${aiResponse.status} | Duration: ${durationSeconds ?? '?'}s`);
            writeMetricsLog(data.sessionId, {
                event: 'response',
                assistanceMode: 'AiAssistance',
                ok: false,
                httpStatus: aiResponse.status,
                durationSeconds,
                latencyMs
            });
            return;
        }

        const responseData = await aiResponse.json();
        const answer = typeof responseData.answer === 'string' ? responseData.answer : null;
        ConsoleLog(`API answer received | Session: ${data.sessionId} | Duration: ${durationSeconds ?? '?'}s | Answer: ${answer ?? '(none)'}`);

        writeMetricsLog(data.sessionId, {
            event:          'response',
            assistanceMode: 'AiAssistance',
            ok:                 true,
            httpStatus:     aiResponse.status,
            durationSeconds,
            latencyMs,
            answer,
            answerLength: answer != null ? answer.length : null
        });

        sendToUnity(responseData);

    } catch (err) {
        ConsoleLog(`Error during API call: ${err}`);
        pendingRequests.delete(data.sessionId);
        writeMetricsLog(data.sessionId, {
            event: 'response',
            assistanceMode: 'AiAssistance',
            ok: false,
            error: String(err)
        });
    }
}

function sendToUnity(message) {
    const target = clients['unity'];
    if (target && target.readyState === WebSocket.OPEN) {
        // Hard-truncate answers longer than MAX_ANSWER_LENGTH characters (AI and HRC answers alike).
        if (message && typeof message.answer === 'string' && message.answer.length > maxAnswerLength) {
            const originalLength = message.answer.length;
            message.answer = message.answer.slice(0, maxAnswerLength);
            ConsoleLog(`Answer truncated for Unity: ${originalLength} -> ${maxAnswerLength} characters.`);
        }
        target.send(JSON.stringify(message));
        ConsoleLog(`Sent -> Unity`);
        ConsoleLog(`Full JSON -> Unity:\n${JSON.stringify(message, null, 2)}`);
    } else {
        ConsoleLog(`No Unity client connected`);
    }
}

function ConsoleLog(msg) {
    const time = new Date().toISOString();
    console.log(`[${time}] ${msg}`);
}

function SanitizeSessionId(rawId) {
    const s = String(rawId ?? "").trim();
    if (s === "" || s === "(no sessionId)" || s === "(no session_id)") return null;
    return s.replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 64);
}

// get sessionId stream 
function GetStream(rawId) {
    let id = SanitizeSessionId(rawId);

    if (!id) 
        id = "unknown-" + new Date().toISOString().replace(/[:.]/g, "-");

    let stream = metricsStreams.get(id);

    if (!stream) {
        fs.mkdirSync(metrics, { recursive: true });
        const file = path.join(metrics, `session_${id}.jsonl`);
        stream = fs.createWriteStream(file, { flags: "a" }); // append, do not overwrite
        metricsStreams.set(id, stream);
        ConsoleLog(`Metrics for session ${id} -> ${file}`);
    }
    return { id, stream };
}

// metrics logging file
function writeMetricsLog(rawId, record) {
    const { id, stream } = GetStream(rawId);
    const entry = { ts: new Date().toISOString(), sessionId: id, ...record };
    stream.write(JSON.stringify(entry) + "\n");
}

function GetLocalIPs() {
    const interfaces = os.networkInterfaces();
    const ips = [];
    for (const name of Object.keys(interfaces)) {
        for (const iface of interfaces[name]) {
            if (iface.family === 'IPv4' && !iface.internal) {
                ips.push(iface.address);
            }
        }
    }
    return ips;
}


function logCurrentClients() {
    ConsoleLog('Current clients:');
    ConsoleLog(`   Browser: ${clients.browser ? 'connected' : 'not connected'}`);
    ConsoleLog(`   Unity:   ${clients.unity ? 'connected' : 'not connected'}`);
}

function shutdown() {
    for (const stream of metricsStreams.values()) {
        stream.end();
    }
    ConsoleLog('All metrics logs closed');
    process.exit(0);
}
process.on('SIGINT', shutdown);
process.on('SIGTERM', shutdown);

// ping intervall
setInterval(() => {
    Object.entries(clients).forEach(([role, ws]) => {
        if (ws && ws.readyState === WebSocket.OPEN) {
            ws.send(JSON.stringify({ type: 'ping' }));
        }
    });
}, 10000);
